### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by FGRibreau** [cgatno/rediserve#2]
Nice work @cgatno :)

Rediserve will be shared in our next [RedisWeekly](http://redisweekly.com) :)

**Comment by cgatno** [comment]
Hey @FGRibreau! Thank you for the kind words, it means a lot :)

That's awesome news! I've been reading up on RedisWeekly digests since I've started working with it more recently, and I'm honored to have rediserve be featured in one of your newsletters! 

(Just a heads up, but I'm getting a security warning when heading to your site. It seems like your SSL cert is authorized to *.redsmin.com so redisweekly.com isn't covered. I've been trying to learn more about server admin. lately, so I just wanted to let you know since I know how annoying those things can be.)

Again, I am extremely excited that my project will be featured in RedisWeekly! If there's anything more you'd like to know about myself or the project, just let me know! The documentation is a little sparse at the moment but I'm hoping to get the chance to flesh it out a bit more tonight, so check back soon!

Thanks again for the heads up!

**Comment by FGRibreau** [comment]
Hello @cgatno,

Great to read that you were already a reader of redisweekly! And sorry I mistyped redisweekly URL, it's indeed http not https :)

**Comment by cgatno** [comment]
Ah okay, that makes a lot more sense! Thanks for clarifying, @FGRibreau!

I'll certainly be looking forward to the next issue :) Again, if you have any questions, etc., don't hesitate to ask!
